In [28]:
#using numpy
import numpy as np
arr=np.array([1,2,4,8,11,12,13,15,19])
#reversing the given data
arr1=np.flip(arr)
print('reversing the data',arr1)

reversing the data [19 15 13 12 11  8  4  2  1]


In [19]:
#using numpy
import numpy as np
#assigning the data
arr=np.array([2,4,8,3,6,9])
arr1=np.array([10,12,14,12,15,18])
#inserting the concatenate function
con=np.concatenate((arr,arr1))
print(' concatenate fuction jointing two array')
print('concatenate function is:',con)

 concatenate fuction jointing two array
concatenate function is: [ 2  4  8  3  6  9 10 12 14 12 15 18]


In [21]:
#using numpy
import numpy as np
#assigning the data
arr=np.array([[2,4,8],[3,6,9]])
arr1=np.array([[10,12,14],[15,18,19]])
#inserting the concatenate with axis=1
con=np.concatenate((arr,arr1),axis=1)
print("concatenate function axis=1")
print(con)

concatenate function axis=1
[[ 2  4  8 10 12 14]
 [ 3  6  9 15 18 19]]


In [26]:
#using numpy
import numpy as np
#assigning the data
arr=np.array([[2,4,8],[3,6,9]])
arr1=np.array([[10,12,14],[15,18,19]])
#inserting the concatenate with axis=0
con=np.concatenate((arr,arr1),axis=0)
print("concatenate function axis=0")
print(con)




concatenate function axis=0
[[ 2  4  8]
 [ 3  6  9]
 [10 12 14]
 [15 18 19]]
